---
title: "FFA_STS"
author: "GuFei"
date: '2020-03-25'
output:
  html_document:
  df_print: paged
---
```{r include=FALSE}
knitr::opts_chunk$set(warning = F, message = F, cache = TRUE)
library(bruceR)
library(psych)
library(ggplot2)
library(ggthemr)
library(RColorBrewer)
library(ggpubr)
```

# 汇总数据
```{r}

rm(list = ls())
load("All.RData")
all_block <- all
load("Alltent.RData")

# 分组统计
analyze <- describeBy(all_block[2:14],list(all_block$position),mat = TRUE)
# 把vars列中的数字替换为名称
varnames <- row.names(analyze)
tempstr <- strsplit(varnames,"[0-9]")
varnames <- sapply(tempstr,'[',1)
analyze$vars <- as.factor(varnames)

# TENT的数据
analyze_tent <- describeBy(all[2:12],list(all$position,all$stimuli),mat = TRUE)
# 把vars列中的数字替换为TR名称
varnames <- row.names(analyze_tent)
varnames <- substr(varnames,1,4)
analyze_tent$vars <- as.factor(varnames)
```

# 分析
## 统计voxel的数量
```{r fig.height=4, fig.width=6}
# 画图时的字体大小
WORD_SIZE = 15

voxel <- subset(all_block, select = c(Sub,Count,position))
#long format data
MANOVA(voxel,subID = 'Sub',dv='Count',within = c("position"))

# 绘图
ggthemr('fresh',layout = "clean")

# 图的标题
title <- 'Voxel Count'
# 提取需要画图的部分
datachosen <- subset(analyze, vars=='Count',select = c(mean,se,vars,group1))
# Error bars represent standard error of the mean
figure <- ggplot(datachosen, aes(x=group1, y=mean)) + 
  #coord_cartesian(ylim=c(0,0.4)) +  # 设置y轴坐标范围
  labs(title = title ,x='Position',y='Voxel Count')+#设置坐标轴
  theme(axis.text.x = element_text(size=WORD_SIZE),  # 设置x轴字体大小，以下同理
        axis.text.y = element_text(size=WORD_SIZE), 
        axis.title.x = element_text(size=WORD_SIZE), 
        axis.title.y = element_text(size=WORD_SIZE),
        legend.title = element_text(size=WORD_SIZE),
        legend.text = element_text(size=WORD_SIZE),
        plot.title = element_text(hjust = 0.5)) + 
  scale_y_continuous(breaks=waiver(),expand = c(0,0))+
  geom_bar(position="dodge", stat="identity") +
  # scale_fill_manual(values = colors[1:2])+ #颜色
  scale_fill_brewer(palette = "Set2",direction = -1)+ #颜色
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se),
                width=.2,color='black',      # Width of the error bars
                position=position_dodge(.9))
print(figure)

```


## 方差分析和画图

```{r fig.height=8, fig.width=12}
# 颜色
gf_color <- c("#A1D99B","#41AB5D","#9ECAE1","#4292C6","#FDAE6B","#F16913","#BCBDDC","#807DBA")
# 绘图
ggthemr('fresh',layout = "clean")
# layout(matrix(c(1,1,2,3),2,2,byrow=T))

# 2个位置
  for (pos in unique(all_block$position)) {
    
    cat("\n作差之后\n")
    # 进行方差分析
    # 选择对应的数据
    data_anova <- subset(all_block,select = c(1:14))
    #更改变量名称
    name <- paste(rep(c('Face_F','Face_H'),each=4),
                  rep(c('Odor_P','Odor_U'),each=2,times=2),
                  rep(c('Visi_I','Visi_V'),times=4),
                  sep = '_')
    name2 <- paste(rep(c('Face_F','Face_H'),each=2),rep(c('Odor_P','Odor_U'),times=2),sep = '_')
    #重命名
    names(data_anova) <- c('Sub',name,'Count',name2)
    
    
    
    
    # 处理没有做差的部分
    data_anova4 <- data_anova[c(1,11:14)]
  
    #方差分析
    MANOVA(data_anova4,dvs =names(data_anova4[-1]),
           dvs.pattern ='Face_(.)_Odor_(.)',
           within=c('Face','Odor'))    
    # %>%
    # EMMEANS("Odor", by="Face")
    # 简单效应
    # MANOVA(data_anova4[seq(2,9,2)],dvs =names(data_anova4[seq(2,9,2)]),
    #        dvs.pattern ='condition_(..)_Face_(.)',
    #        within=c('Condition','Face')) 
    # 
    
    
    
    cat("\n全部8个条件\n")
    # 进行方差分析
    # 选择对应的数据没有做差的部分
    print(paste0(pos))
    data_anova8 <- data_anova[c(1:9)]
   
    #方差分析
    MANOVA(data_anova8,dvs =names(data_anova8[-1]),
           dvs.pattern ='Face_(.)_Odor_(.)_Visi_(.)',
           within=c('Face','Odor','Visi'))    
    
    
    
    
    cat("\n绘图\n")
    
    # 图的标题
    title <- paste0(pos)
    # 提取需要画图的部分
    datachosen <- subset(analyze,group1==pos 
                         & vars%in%c('FP','FU','HP','HU'),select = c(mean,se,vars))
    # Error bars represent standard error of the mean
    figure_4 <- ggplot(datachosen, aes(x=vars, y=mean)) + 
      #coord_cartesian(ylim=c(0,0.4)) +  # 设置y轴坐标范围
      labs(title = title ,x='Condition',y='Mean β',fill='ROI')+#设置坐标轴
      theme(axis.text.x = element_text(size=WORD_SIZE),  # 设置x轴字体大小，以下同理
            axis.text.y = element_text(size=WORD_SIZE), 
            axis.title.x = element_text(size=WORD_SIZE), 
            axis.title.y = element_text(size=WORD_SIZE),
            legend.title = element_text(size=WORD_SIZE),
            legend.text = element_text(size=WORD_SIZE),
            plot.title = element_text(hjust = 0.5)) + 
      scale_y_continuous(expand = c(0,0))+
      geom_bar(position="dodge", stat="identity") +
      # scale_fill_manual(values = colors[1:2])+ #颜色
      scale_fill_brewer(palette = "Set2",direction = -1)+ #颜色
      geom_errorbar(aes(ymin=mean-se, ymax=mean+se),
                    width=.2,color='black',      # Width of the error bars
                    position=position_dodge(.9))
    
    
    
    # 8个条件没有作差的
    datachosen <- subset(analyze,group1==pos
                         & vars%in%c('FPI','FPV','FUI','FUV','HPI','HPV','HUI','HUV'),
                         select = c(mean,se,vars))
    # Error bars represent standard error of the mean
    figure_8 <- ggplot(datachosen, aes(x=vars, y=mean)) + 
      # coord_cartesian(ylim=c(-0.5,0.5)) +  # 设置y轴坐标范围
      labs(title = title ,x='Condition',y='Mean β',fill='ROI')+#设置坐标轴
      theme(axis.text.x = element_text(size=WORD_SIZE),  # 设置x轴字体大小，以下同理
            axis.text.y = element_text(size=WORD_SIZE), 
            axis.title.x = element_text(size=WORD_SIZE), 
            axis.title.y = element_text(size=WORD_SIZE),
            legend.title = element_text(size=WORD_SIZE),
            legend.text = element_text(size=WORD_SIZE),
            plot.title = element_text(hjust = 0.5)) + 
      scale_y_continuous(expand = c(0,0))+
      geom_bar(position="dodge", stat="identity") +
      # scale_fill_manual(values = colors[1:2])+ #颜色
      scale_fill_brewer(palette = "Set2",direction = -1)+ #颜色
      geom_errorbar(aes(ymin=mean-se, ymax=mean+se),
                    width=.2,color='black',      # Width of the error bars
                    position=position_dodge(.9))
      
    # TENT
    # 选择数据
    # datachosen <- subset(all,position==pos & valance==val,select = c(1:12,14,16))
    # 作差之后的结果
    pd <- position_dodge(0.9)
    datachosen <- subset(analyze_tent,group1==pos
                         & group2%in%c('FP','FU','HP','HU'),
                         select = c(mean,se,vars,group2))
    figtent_4 <- ggplot(datachosen, aes(x=vars, y=mean,
                           group=group2,color=group2)) + 
      labs(x='TR',y='Mean β',color='Condition')+#设置坐标轴,linetype='ROI'
      # scale_color_brewer(palette = "Set2",direction = -1)+ #颜色
      scale_color_manual(values = gf_color[seq(2,8,2)])+ #自选颜色
      # scale_linetype_manual(values=c("solid", "longdash"))+
      theme(axis.text.x = element_text(size=WORD_SIZE),  # 设置x轴字体大小，以下同理
            axis.text.y = element_text(size=WORD_SIZE), 
            axis.title.x = element_text(size=WORD_SIZE), 
            axis.title.y = element_text(size=WORD_SIZE),
            legend.title = element_text(size=WORD_SIZE),
            legend.text = element_text(size=WORD_SIZE),
            text = element_text(size=WORD_SIZE),
            plot.title = element_text(hjust = 0.5))+ 
      scale_x_discrete(labels=as.character(0:10),expand = c(0,0))+
      geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.1,position = pd) +
      geom_line(position = pd) +
      geom_point(position = pd)
    # 没有作差的结果
    datachosen <- subset(analyze_tent,group1==pos
                         & group2%in%c('FPI','FPV','FUI','FUV','HPI','HPV','HUI','HUV'),
                         select = c(mean,se,vars,group2))
    
    figtent_8 <- ggplot(datachosen, aes(x=vars, y=mean,
                                        group=group2,color=group2)) + 
      labs(x='TR',y='Mean β',color='Condition')+#设置坐标轴,linetype='ROI'
      # scale_color_brewer(palette = "Set2",direction = -1)+ #颜色
      scale_color_manual(values = gf_color)+ #自选颜色
      # scale_linetype_manual(values=c("solid", "longdash"))+
      theme(axis.text.x = element_text(size=WORD_SIZE),  # 设置x轴字体大小，以下同理
            axis.text.y = element_text(size=WORD_SIZE), 
            axis.title.x = element_text(size=WORD_SIZE), 
            axis.title.y = element_text(size=WORD_SIZE),
            legend.title = element_text(size=WORD_SIZE),
            legend.text = element_text(size=WORD_SIZE),
            text = element_text(size=WORD_SIZE),
            plot.title = element_text(hjust = 0.5))+ 
      scale_x_discrete(labels=as.character(0:10),expand = c(0,0))+
      geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.1,position = pd) +
      geom_line(position = pd) +
      geom_point(position = pd)
    
    # 合并几个图到一个里面
    # ggarrange(p2,ggarrange(p1,p3,ncol=2,labels=c("B","C")),nrow=2,labels="A")
    block <- ggarrange(figure_4,figure_8,ncol = 2,labels=c("A","B"),widths = c(3,4))
    tent <- ggarrange(figtent_4,figtent_8,ncol = 2,labels=c("C","D"))
    print(ggarrange(block,tent,nrow = 2,heights = c(1,3)))
    # 测试保存图片
    # jpeg(file="myplot.jpeg",width = 1920,height = 1080)
    # ggarrange(figure_4,figure_8,ncol = 2,labels=c("A","B"),widths = c(1,2))
    # dev.off()
}
# # 可以查看对应主题的颜色
# colour_plot(swatch())
# colour_plot(ggthemr("pale"))
# colour_plot(ggthemr("greyscale"))
# colour_plot(ggthemr("solarized"))
# # colorbrewer选择颜色，生成颜色
# display.brewer.all_block()
# colors <- brewer.pal(8,"Set2")
# colour_plot(colors)
# # colors是自带颜色函数
# colors()
```
